#!/usr/bin/env php
<?php

/**
 * This is an example of a CLI application
 * 
 * Run "php ./cli --help" to get help
 */

// composer autoload
require realpath(__DIR__.'/../vendor/autoload.php');

use Libcast\JobQueue\Command\JobQueueApplication;
use Libcast\JobQueue\Queue\QueueFactory;
use Predis\Client;

// include the Jobs you developped
foreach (glob(__DIR__.'/Job/*Job.php') as $job) {
    include $job;
}

// list your worker pathes to help with the CLI's worker features
$workers = array(
    realpath(__DIR__).'/worker',
);

// list the profiles to help with the CLI's worker features
$profiles = array(
    'dummy-stuff',
    'notsodummy',
);

// get a Queue instance
$redis = new Client('tcp://localhost:6379');
$queue = QueueFactory::load($redis);

$application = new JobQueueApplication($queue, array(
    'workers'   => $workers,
    'profiles'  => $profiles,
));
$application->run();