#!/usr/bin/env php
<?php

/**
 * This is a Worker example.
 * This Worker shoul be run as a daemon.
 * See /example/worker.conf to get an example of an upstart job (Ubuntu/Debian)
 * 
 * The Logger should send logs in both a worker-dedicated and common streams
 */

// settings :
$name                 = 'libcast_worker';       // string
$profiles             = array('dummy-stuff');   // array of profile(s)
$component_path       = __DIR__.'/..';          // path to component root
$logs_path            = __DIR__.'/../log';      // path to logs directory
$provider             = 'redis';                // DB (only 'redis' for now)
$provider_parameters  = array(                  // DB settings:
    'host'            => 'localhost',           // - redis hostname
    'port'            => 6379,                  // - redis port
);
// end of settings

require realpath("$component_path/vendor/autoload.php");

use Monolog\Logger;
use Monolog\Handler\StreamHandler;

use Libcast\JobQueue\Queue\QueueFactory;
use Libcast\JobQueue\Worker\Worker;

// setup the Monolog logger
$logger = new Logger($name);
$logger->pushHandler(new StreamHandler("$logs_path/$name.log", Logger::INFO));
$logger->pushHandler(new StreamHandler("$logs_path/common.log", Logger::INFO));

// get a Queue instance
$queueFactory = new QueueFactory($provider, $provider_parameters, $logger);

$queue = $queueFactory->getQueue();

// setup and start the Worker
$worker = new Worker($name, $queue, $profiles, $logger);
$worker->run();