parameters:
  redis_dsn: '%env(JOBQUEUE_REDIS_DSN)%'

services:
  predis:
    class: \Predis\Client
    arguments: ['%redis_dsn%']

  queue:
    public: true
    class: \JobQueue\Infrastructure\RedisQueue
    arguments: ['@predis']

  dispatcher:
    public: true
    class: \Symfony\Component\EventDispatcher\EventDispatcher
